"""
this class autogenerated for registering app names
"""


from django.apps import AppConfig


class CreateuserConfig(AppConfig):
    """
    Registered application name as createuser
    """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'createuser'
